name: Deploy

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          path: recipes

      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install generator
        run: >
          pip install
          git+https://github.com/kalekundert/fitzkundert_recipes_static_site_generator.git

      - name: Build website
        run: fitzkundert_recipes recipes output
        env:
          FITZKUNDERT_RECIPES_EDIT_URL: >-
            https://github.com/kalekundert/fitzkundert_recipes/edit/main/{path}

      - name: Deploy to Cloudflare Pages
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          command: pages deploy output --project-name=fitzkundert-recipes
